name: Static Code Check

on:
  push:
    branches:
      - main

jobs:
  lint-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install eslint html-validator-cli stylelint stylelint-config-standard --save-dev

      - name: Lint JavaScript
        run: npx eslint ./js || echo "JS linting failed"

      - name: Validate HTML
        run: html-validator --file=index.html --verbose || echo "HTML validation failed"

      - name: Lint CSS
        run: npx stylelint "**/*.css" || echo "CSS linting failed"